"""plugins 命令组：插件管理"""

from __future__ import annotations

import keyword
import re
from pathlib import Path

import typer
from rich.table import Table

from souwen.cli._common import _run_async, console, redact_cli_text, redact_cli_value
from souwen.plugin_manager import (
    DEFAULT_PLUGIN_HEALTH_TIMEOUT_SECONDS,
    collect_plugin_health,
    run_plugin_health,
)

_PLUGIN_NAME_RE = re.compile(r"^[a-z](?:[a-z0-9_]*[a-z0-9])?$")
_SAFE_PIP_FAILURE_MESSAGES = {
    "插件安装功能未启用，请设置 SOUWEN_ENABLE_PLUGIN_INSTALL=1。",
    "插件卸载功能未启用，请设置 SOUWEN_ENABLE_PLUGIN_INSTALL=1。",
    "非法插件包名。",
    "插件包不在允许列表中。",
    "安装插件失败，请查看服务端日志。",
    "卸载插件失败，请查看服务端日志。",
}

plugins_app = typer.Typer(
    name="plugins",
    help="插件管理 — 列表、启用/禁用、安装/卸载、重载、健康检查",
    no_args_is_help=True,
)


def _normalize_cli_arg(value: str, name: str) -> str:
    """Strip a required CLI argument and reject blank values."""
    normalized = value.strip()
    if not normalized:
        console.print(f"[red]{name} 不能是空字符串。[/red]")
        raise typer.Exit(code=1)
    return normalized


def _safe_pip_failure_message(output: object) -> str:
    """Return a safe pip operation failure message for terminal output."""
    message = str(output or "").strip()
    if message in _SAFE_PIP_FAILURE_MESSAGES:
        return message
    return "操作失败，详见服务端日志"


def _safe_plugin_reload_error_message() -> str:
    """Return a safe plugin reload failure message for terminal output."""
    return "插件加载失败，请查看日志。"


def _safe_health_field(key: str, value: object) -> str:
    """Return a redacted health field value for terminal output."""
    redacted = redact_cli_value({key: value})
    if isinstance(redacted, dict):
        value = redacted.get(key)
    return redact_cli_text(value)


def _validate_scaffold_name(name: str) -> str:
    """Normalize and validate the package name used by ``plugins new``."""
    name = _normalize_cli_arg(name, "name")
    if _PLUGIN_NAME_RE.fullmatch(name) is None:
        console.print(
            "[red]插件名称必须以小写字母开头、字母或数字结尾，且只能包含小写字母、数字和下划线。[/red]"
        )
        raise typer.Exit(code=1)
    if keyword.iskeyword(name):
        console.print("[red]插件名称不能是 Python 关键字。[/red]")
        raise typer.Exit(code=1)
    return name


def _render_health_cell(
    name: str,
    status: str,
    health_map: dict[str, dict[str, object]],
) -> str:
    """Render the health cell for the list table."""
    if status != "loaded":
        return "[dim]—[/dim]"
    info = health_map.get(name)
    if info is None:
        return "[dim]?[/dim]"
    state = str(info.get("status", "")).lower()
    if state in {"ok", "healthy"}:
        return "[green]✅ ok[/green]"
    if state in {"degraded", "warn", "warning"}:
        return f"[yellow]⚠ {state}[/yellow]"
    if state in {"not_loaded"}:
        return "[dim]未加载[/dim]"
    return f"[red]❌ {state or 'error'}[/red]"


def _plugin_scaffold_files(name: str) -> dict[Path, str]:
    """Return the files for a new plugin scaffold."""
    project_name = name.replace("_", "-")
    return {
        Path("pyproject.toml"): f"""[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "souwen-plugin-{project_name}"
version = "0.1.0"
description = "SouWen plugin: {name}"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8"]

[project.entry-points."souwen.plugins"]
{name} = "{name}:plugin"

[tool.setuptools.packages.find]
include = ["{name}*"]
""",
        Path("souwen-plugin.json"): f"""{{
  "$schema": "https://github.com/BlueSkyXN/SouWen/blob/v2-dev/docs/plugin-manifest.schema.json",
  "schema_version": 1,
  "name": "{name}",
  "entry_point": "{name}:plugin",
  "version": "0.1.0",
  "api_version": "1",
  "description": "SouWen plugin: {name}",
  "adapters": [
    {{
      "name": "{name}",
      "domain": "fetch",
      "integration": "scraper",
      "description": "Example fetch provider scaffold generated by SouWen",
      "config_field": null,
      "methods": ["fetch"],
      "needs_config": false,
      "auth_requirement": "none",
      "default_enabled": false,
      "tags": ["external_plugin"],
      "risk_level": "low",
      "distribution": "plugin",
      "stability": "stable",
      "catalog_visibility": "public"
    }}
  ]
}}
""",
        Path(name) / "__init__.py": f'''"""SouWen plugin scaffold for {name}."""

from __future__ import annotations

import logging

from souwen.plugin import Plugin
from souwen.registry.adapter import MethodSpec, SourceAdapter
from souwen.registry.loader import lazy

logger = logging.getLogger(__name__)

adapter = SourceAdapter(
    name="{name}",
    domain="fetch",
    integration="scraper",
    description="Example fetch provider scaffold generated by SouWen",
    config_field=None,
    client_loader=lazy("{name}.client:{name.title().replace("_", "")}Client"),
    methods={{"fetch": MethodSpec("fetch")}},
    needs_config=False,
    default_enabled=False,
    tags=frozenset({{"external_plugin"}}),
)


def health_check() -> dict[str, str]:
    """Return a lightweight plugin health status."""
    return {{"status": "ok"}}


plugin = Plugin(
    name="{name}",
    version="0.1.0",
    adapters=[adapter],
    health_check=health_check,
)


try:
    from .handler import register

    register()
except ImportError as exc:
    logger.warning("可选 fetch handler 注册不可用: %s", exc, exc_info=True)
except Exception as exc:
    logger.warning("可选 fetch handler 注册失败: %s", exc, exc_info=True)
''',
        Path(name) / "client.py": f'''"""Client implementation for the {name} plugin."""

from __future__ import annotations


class {name.title().replace("_", "")}Client:
    """Minimal example client used by the generated fetch handler."""

    async def __aenter__(self) -> "{name.title().replace("_", "")}Client":
        """Enter the client context."""
        return self

    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> None:
        """Exit the client context."""
        return None

    async def fetch(self, url: str, *, timeout: float = 30.0) -> str:
        """Fetch one URL and return markdown content.

        Replace this method with provider-specific API calls when integrating a
        real service. The scaffold keeps deterministic behavior so the package
        can be installed and smoke-tested immediately.
        """
        return (
            "# {name} fetch result\\n\\n"
            f"- URL: {{url}}\\n"
            f"- Timeout: {{timeout:.1f}}s\\n"
            "- Status: scaffold handler executed successfully\\n"
        )
''',
        Path(name) / "handler.py": f'''"""Fetch handler registration for the {name} plugin."""

from __future__ import annotations

from typing import Any

from souwen.models import FetchResponse, FetchResult

from .client import {name.title().replace("_", "")}Client


async def {name}_handler(
    urls: list[str],
    timeout: float = 30.0,
    **kwargs: Any,
) -> FetchResponse:
    """Fetch URLs through the {name} provider."""
    del kwargs
    results: list[FetchResult] = []
    async with {name.title().replace("_", "")}Client() as client:
        for url in urls:
            content = await client.fetch(url, timeout=timeout)
            results.append(
                FetchResult(
                    url=url,
                    final_url=url,
                    source="{name}",
                    title=f"{name} fetch result",
                    content=content,
                    content_format="markdown",
                    snippet=content.splitlines()[0] if content else "",
                    raw={{"provider": "{name}", "scaffold": True}},
                )
            )
    return FetchResponse(
        urls=urls,
        results=results,
        total=len(results),
        total_ok=len(results),
        total_failed=0,
        provider="{name}",
    )


def register() -> None:
    """Register the fetch handler when SouWen loads this plugin."""
    from souwen.web.fetch import register_fetch_handler

    register_fetch_handler("{name}", {name}_handler)
''',
        Path("tests") / f"test_{name}.py": f'''"""Tests for the {name} SouWen plugin."""

from __future__ import annotations

import asyncio

from souwen.testing import assert_valid_plugin

from {name} import plugin
from {name}.handler import {name}_handler


def test_plugin_contract() -> None:
    assert_valid_plugin(plugin)


def test_fetch_handler_smoke() -> None:
    response = asyncio.run({name}_handler(["https://example.com"], timeout=5))

    assert response.provider == "{name}"
    assert response.total_ok == 1
    assert response.results[0].source == "{name}"
    assert "https://example.com" in response.results[0].content
''',
        Path("README.md"): f"""# {name}

SouWen plugin scaffold for `{name}`.

## Develop

```bash
python -m pip install -e ".[dev]"
pytest
```

Optional metadata manifest validation from a SouWen source checkout:

```bash
python tools/validate_plugin_manifest.py /path/to/{name}/souwen-plugin.json
```

## Register with SouWen

This package exposes the `{name}` entry point in the `souwen.plugins` group:

```toml
[project.entry-points."souwen.plugins"]
{name} = "{name}:plugin"
```

The generated provider is intentionally deterministic: `{name}/client.py`
returns markdown that includes the requested URL, and `{name}/handler.py`
registers it as a SouWen fetch provider. Replace the client method with real
provider calls, then run the contract and handler smoke tests.
""",
    }


@plugins_app.command("new")
def new_cmd(
    name: str = typer.Argument(
        ...,
        help="新插件名称（小写字母开头，字母或数字结尾，可含数字和下划线，不能是 Python 关键字）",
    ),
) -> None:
    """创建一个新的 SouWen 插件项目骨架。"""
    name = _validate_scaffold_name(name)

    target_dir = Path(name)
    if target_dir.exists():
        console.print(f"[red]目标目录 {name!r} 已存在。[/red]")
        raise typer.Exit(code=1)

    for rel_path, content in _plugin_scaffold_files(name).items():
        path = target_dir / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    console.print(f"[green]✅ 已创建插件项目: {target_dir}[/green]")
    console.print(
        f"下一步: cd {target_dir} && python -m pip install -e '.[dev]'",
        style="dim",
        markup=False,
    )


@plugins_app.command("list")
def list_cmd(
    show_health: bool = typer.Option(
        False,
        "--health",
        help="并发执行已加载插件的 health_check 并附加状态列。",
    ),
    health_timeout: float = typer.Option(
        DEFAULT_PLUGIN_HEALTH_TIMEOUT_SECONDS,
        "--health-timeout",
        help="单个 health_check 的超时秒数。",
    ),
) -> None:
    """列出所有插件"""
    from souwen.plugin_manager import is_restart_required, list_plugins

    plugins = list_plugins()

    if is_restart_required():
        console.print("[bold yellow]⚠ 插件状态已变更，重启后完全生效。[/bold yellow]")
        console.print()

    if not plugins:
        console.print("[dim]未发现任何插件。[/dim]")
        return

    health_map: dict[str, dict[str, object]] = {}
    if show_health:
        loaded_names = [p.name for p in plugins if p.status == "loaded"]
        if loaded_names:
            health_map = _run_async(collect_plugin_health(loaded_names, timeout=health_timeout))

    table = Table(title="🔌 SouWen 插件", show_lines=True)
    table.add_column("Name", style="cyan")
    table.add_column("Status", justify="center")
    table.add_column("Source", style="magenta")
    table.add_column("Version", style="dim")
    if show_health:
        table.add_column("Health", justify="center")
    table.add_column("Description", style="dim")

    status_icons = {
        "loaded": "[green]✅ 已加载[/green]",
        "available": "[yellow]📦 可用[/yellow]",
        "disabled": "[red]⛔ 禁用[/red]",
        "error": "[red]❌ 错误[/red]",
    }

    for p in plugins:
        row = [
            p.name,
            status_icons.get(p.status, p.status),
            p.source,
            p.version or "-",
        ]
        if show_health:
            row.append(_render_health_cell(p.name, p.status, health_map))
        row.append(p.description or "-")
        table.add_row(*row)

    console.print(table)


@plugins_app.command("info")
def info_cmd(
    name: str = typer.Argument(..., help="插件名称"),
) -> None:
    """查看插件详情"""
    from souwen.plugin_manager import get_plugin_info

    name = _normalize_cli_arg(name, "name")
    info = get_plugin_info(name)
    if info is None:
        console.print(f"[red]插件 {name!r} 未找到。[/red]")
        raise typer.Exit(code=1)

    console.print(f"[bold cyan]🔌 {info.name}[/bold cyan]")
    console.print(f"  状态:    {info.status}")
    console.print(f"  来源:    {info.source}")
    console.print(f"  包名:    {info.package or '-'}")
    console.print(f"  版本:    {info.version or '-'}")
    console.print(f"  官方:    {'是' if info.first_party else '否'}")
    console.print(f"  描述:    {info.description or '-'}")
    if info.source_adapters:
        console.print(f"  数据源:  {', '.join(info.source_adapters)}")
    if info.fetch_handlers:
        console.print(f"  处理器:  {', '.join(info.fetch_handlers)}")
    if info.error:
        console.print(f"  [red]错误:    {info.error}[/red]")
    if info.restart_required:
        console.print("  [yellow]⚠ 需要重启[/yellow]")


@plugins_app.command("enable")
def enable_cmd(
    name: str = typer.Argument(..., help="插件名称"),
) -> None:
    """启用插件（重启后生效）"""
    from souwen.plugin_manager import enable_plugin

    name = _normalize_cli_arg(name, "name")
    result = enable_plugin(name)
    if result["success"]:
        console.print(f"[green]✅ {result['message']}[/green]")
    else:
        console.print(f"[red]❌ {result['message']}[/red]")
        raise typer.Exit(code=1)


@plugins_app.command("disable")
def disable_cmd(
    name: str = typer.Argument(..., help="插件名称"),
) -> None:
    """禁用插件（重启后生效）"""
    from souwen.plugin_manager import disable_plugin_async

    name = _normalize_cli_arg(name, "name")
    result = _run_async(disable_plugin_async(name))
    if result["success"]:
        console.print(f"[green]✅ {result['message']}[/green]")
    else:
        console.print(f"[red]❌ {result['message']}[/red]")
        raise typer.Exit(code=1)


@plugins_app.command("install")
def install_cmd(
    package: str = typer.Argument(..., help="插件包名（如 superweb2pdf）"),
) -> None:
    """安装插件（需 SOUWEN_ENABLE_PLUGIN_INSTALL=1）"""
    from souwen.plugin_manager import install_plugin

    package = _normalize_cli_arg(package, "package")
    console.print(f"[dim]正在安装 {package}...[/dim]")
    result = _run_async(install_plugin(package))
    if result["success"]:
        console.print("[green]✅ 安装成功。重启后生效。[/green]")
    else:
        console.print(f"[red]❌ 安装失败: {_safe_pip_failure_message(result.get('output'))}[/red]")
        raise typer.Exit(code=1)


@plugins_app.command("uninstall")
def uninstall_cmd(
    package: str = typer.Argument(..., help="插件包名（如 superweb2pdf）"),
) -> None:
    """卸载插件（需 SOUWEN_ENABLE_PLUGIN_INSTALL=1）"""
    from souwen.plugin_manager import uninstall_plugin

    package = _normalize_cli_arg(package, "package")
    console.print(f"[dim]正在卸载 {package}...[/dim]")
    result = _run_async(uninstall_plugin(package))
    if result["success"]:
        console.print("[green]✅ 卸载成功。重启后生效。[/green]")
    else:
        console.print(f"[red]❌ 卸载失败: {_safe_pip_failure_message(result.get('output'))}[/red]")
        raise typer.Exit(code=1)


@plugins_app.command("reload")
def reload_cmd() -> None:
    """重新扫描插件（追加模式）"""
    from souwen.plugin_manager import reload_plugins

    result = reload_plugins()
    console.print(f"[green]{result['message']}[/green]")
    if result["loaded"]:
        console.print(f"  新增: {', '.join(result['loaded'])}")
    if result["errors"]:
        for err in result["errors"]:
            console.print(
                f"  [red]错误: {err.get('name', '?')} — {_safe_plugin_reload_error_message()}[/red]"
            )
        raise typer.Exit(code=1)


@plugins_app.command("health")
def health_cmd(
    name: str = typer.Argument(..., help="插件名称（必须已加载）"),
    timeout: float = typer.Option(
        DEFAULT_PLUGIN_HEALTH_TIMEOUT_SECONDS,
        "--timeout",
        "-t",
        help="health_check 超时秒数。",
    ),
) -> None:
    """运行单个插件的 health_check（对应 GET /admin/plugins/{name}/health）。"""
    name = _normalize_cli_arg(name, "name")
    result = _run_async(run_plugin_health(name, timeout=timeout, include_error_detail=False))
    state = str(result.get("status", "")).lower()
    if state == "not_loaded":
        console.print(f"[red]❌ {result.get('message', '插件未加载')}[/red]")
        raise typer.Exit(code=1)
    if state in {"ok", "healthy"}:
        console.print(f"[green]✅ {name} 健康[/green]")
    elif state in {"degraded", "warn", "warning"}:
        console.print(f"[yellow]⚠ {name}: {state}[/yellow]")
    else:
        console.print(f"[red]❌ {name}: {state or 'error'}[/red]")
    for key, value in result.items():
        if key == "status":
            continue
        console.print(f"  {key}: {_safe_health_field(key, value)}")
    if state not in {"ok", "healthy", "degraded", "warn", "warning"}:
        raise typer.Exit(code=1)
