"""Generate value-free B0 Provider v2 spec-review drafts from the inventory."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_DIR = REPO_ROOT / "docs" / "internal" / "provider-migrations"
DEFAULT_JSON_PATH = ARTIFACT_DIR / "b0-spec-drafts.json"
DEFAULT_MARKDOWN_PATH = ARTIFACT_DIR / "b0-spec-drafts.md"
SCHEMA_VERSION = 1
GENERATOR_VERSION = "b0-provider-spec-drafts-v1"


def _inventory_module():
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from tools import provider_migration_inventory

    return provider_migration_inventory


def build_drafts(inventory: dict[str, Any] | None = None) -> dict[str, Any]:
    """Build review-only drafts without importing or constructing legacy clients."""

    source_inventory = inventory or _inventory_module().build_inventory()
    drafts: list[dict[str, Any]] = []
    existing_provider_specs: list[dict[str, Any]] = []
    for record in source_inventory["records"]:
        if record["migration_status"] == "migrated":
            existing_provider_specs.append(
                {
                    "source_id": record["source_id"],
                    "provider_manifest_id": record["provider_manifest_id"],
                    "target_package": record["target_package"],
                    "target_manifest_id": record["target_manifest_id"],
                    "target_adapter_id": record["target_adapter_id"],
                    "target_capability": record["target_capability"],
                    "target_spec_identity": record["target_spec_identity"],
                    "target_spec_path": record["target_spec_path"],
                    "target_spec_reason": record["target_spec_reason"],
                    "specification_status": "existing_provider_manifest",
                }
            )
            continue
        drafts.append(
            {
                "source_id": record["source_id"],
                "batch": record["batch"],
                "migration_status": record["migration_status"],
                "capabilities": record["capabilities"],
                "auth_requirement": record["auth_requirement"],
                "credential_fields": record["credential_fields"],
                "legacy_loader": record["legacy_loader"],
                "provider_manifest_id": record["provider_manifest_id"],
                "target_package": record["target_package"],
                "target_manifest_id": record["target_manifest_id"],
                "target_adapter_id": record["target_adapter_id"],
                "target_capability": record["target_capability"],
                "target_spec_identity": record["target_spec_identity"],
                "target_spec_path": record["target_spec_path"],
                "target_spec_reason": record["target_spec_reason"],
                "request_mapping": {"review_required": True},
                "response_mapping": {"review_required": True},
                "error_mapping": {"review_required": True},
                "transport": {"review_required": True},
            }
        )
    return {
        "schema_version": SCHEMA_VERSION,
        "generator_version": GENERATOR_VERSION,
        "source_fingerprint": source_inventory["source_fingerprint"],
        "inventory_registry_sha256": source_inventory["registry_sha256"],
        "draft_count": len(drafts),
        "existing_provider_spec_count": len(existing_provider_specs),
        "drafts": drafts,
        "existing_provider_specs": existing_provider_specs,
    }


def render_json(drafts: dict[str, Any] | None = None) -> str:
    return json.dumps(drafts or build_drafts(), ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def render_markdown(drafts: dict[str, Any] | None = None) -> str:
    data = drafts or build_drafts()
    lines = [
        "# B0 Provider v2 spec review drafts",
        "",
        "Generated by `tools/gen_provider_spec_drafts.py`; do not implement an adapter directly",
        "from this file. It contains only pending sources; migrated sources are listed separately",
        "as existing Provider v2 manifest references. Every request, response, error, and transport",
        "mapping in a draft remains",
        "`review_required` until a maintainer validates it against the legacy client contract.",
        "",
        f"- Schema version: `{data['schema_version']}`",
        f"- Generator version: `{data['generator_version']}`",
        f"- Draft count: `{data['draft_count']}`",
        f"- Existing Provider v2 specs: `{data['existing_provider_spec_count']}`",
        f"- Inventory fingerprint: `{data['inventory_registry_sha256']}`",
        f"- Combined input fingerprint: `{data['source_fingerprint']['input_sha256']}`",
        "",
        "| Source | Batch | Status | Capabilities | Auth | Legacy loader | Existing manifest | Mapping review |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for draft in data["drafts"]:
        lines.append(
            "| `{source_id}` | `{batch}` | `{status}` | {capabilities} | "
            "`{auth}` | `{loader}` | {manifest} | required |".format(
                source_id=draft["source_id"],
                batch=draft["batch"],
                status=draft["migration_status"],
                capabilities=", ".join(f"`{item}`" for item in draft["capabilities"]),
                auth=draft["auth_requirement"],
                loader=draft["legacy_loader"],
                manifest=(
                    f"`{draft['provider_manifest_id']}`" if draft["provider_manifest_id"] else "—"
                ),
            )
        )
    lines.extend(
        [
            "",
            "## Existing Provider v2 specifications",
            "",
            "These migrated sources are references only, not review-required B0 drafts.",
            "",
            "| Source | Package | Manifest | Adapter | Capability | Spec identity | Spec path | No-spec reason | Specification status |",
            "|---|---|---|---|---|---|---|---|---|",
        ]
    )
    for spec in data["existing_provider_specs"]:
        lines.append(
            "| `{source_id}` | `{target_package}` | `{target_manifest_id}` | "
            "`{target_adapter_id}` | `{target_capability}` | {target_spec_identity} | "
            "{target_spec_path} | {target_spec_reason} | `{specification_status}` |".format(
                **{
                    **spec,
                    "target_spec_identity": (
                        f"`{spec['target_spec_identity']}`" if spec["target_spec_identity"] else "—"
                    ),
                    "target_spec_path": (
                        f"`{spec['target_spec_path']}`" if spec["target_spec_path"] else "—"
                    ),
                    "target_spec_reason": spec["target_spec_reason"] or "—",
                }
            )
        )
    return "\n".join(lines) + "\n"


def _check(path: Path, expected: str) -> bool:
    return path.is_file() and path.read_text(encoding="utf-8") == expected


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write", action="store_true", help="write controlled JSON and Markdown artifacts"
    )
    parser.add_argument(
        "--check", action="store_true", help="fail when controlled artifacts are stale"
    )
    parser.add_argument("--json-path", type=Path, default=DEFAULT_JSON_PATH)
    parser.add_argument("--markdown-path", type=Path, default=DEFAULT_MARKDOWN_PATH)
    args = parser.parse_args(argv)
    if args.write and args.check:
        parser.error("--write and --check are mutually exclusive")

    drafts = build_drafts()
    json_text = render_json(drafts)
    markdown_text = render_markdown(drafts)
    if args.write:
        args.json_path.parent.mkdir(parents=True, exist_ok=True)
        args.markdown_path.parent.mkdir(parents=True, exist_ok=True)
        args.json_path.write_text(json_text, encoding="utf-8")
        args.markdown_path.write_text(markdown_text, encoding="utf-8")
        print(f"WROTE: {args.json_path}")
        print(f"WROTE: {args.markdown_path}")
    elif args.check:
        stale = [
            str(path)
            for path, expected in ((args.json_path, json_text), (args.markdown_path, markdown_text))
            if not _check(path, expected)
        ]
        if stale:
            print("STALE: " + ", ".join(stale), file=sys.stderr)
            return 1
        print(f"OK: {drafts['draft_count']} B0 spec review drafts")
    else:
        print(markdown_text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
